/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "e:\\personal_code\\GitHub\\vue-press-blog\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-62c2a688",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-62c2a688").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-691e23ca",
    path: "/guide/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-691e23ca").then(next)
    },
  },
  {
    path: "/guide/index.html",
    redirect: "/guide/"
  },
  {
    name: "v-659b7682",
    path: "/zh-CN/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-659b7682").then(next)
    },
  },
  {
    path: "/zh-CN/index.html",
    redirect: "/zh-CN/"
  },
  {
    name: "v-7ecaf5ec",
    path: "/zh-CN/guide/js/123.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7ecaf5ec").then(next)
    },
  },
  {
    name: "v-6be1834e",
    path: "/guide/vue/optimizeVue.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6be1834e").then(next)
    },
  },
  {
    name: "v-0d1e1c6c",
    path: "/zh-CN/guide/vue/optimizeVue.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0d1e1c6c").then(next)
    },
  },
  {
    name: "v-fa665cdc",
    path: "/zh-CN/guide/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-fa665cdc").then(next)
    },
  },
  {
    path: "/zh-CN/guide/index.html",
    redirect: "/zh-CN/guide/"
  },
  {
    path: '*',
    component: GlobalLayout
  }
]