/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "",
  "description": "",
  "base": "/blog/",
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroImage": "/logo.JPG",
        "actionText": "Get Started →",
        "actionLink": "/guide/"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-62c2a688",
      "path": "/",
      "lastUpdated": "8/29/2019, 4:56:00 PM"
    },
    {
      "title": "优化 Vue 项目",
      "frontmatter": {},
      "regularPath": "/guide/vue/%E4%BC%98%E5%8C%96Vue%E9%A1%B9%E7%9B%AE.html",
      "relativePath": "guide/vue/优化Vue项目.md",
      "key": "v-5caf73da",
      "path": "/guide/vue/%E4%BC%98%E5%8C%96Vue%E9%A1%B9%E7%9B%AE.html",
      "lastUpdated": "8/29/2019, 11:17:42 AM"
    },
    {
      "frontmatter": {},
      "regularPath": "/guide/",
      "relativePath": "guide/README.md",
      "key": "v-691e23ca",
      "path": "/guide/",
      "lastUpdated": "8/28/2019, 6:12:33 PM"
    },
    {
      "title": "常用的 JS 技巧",
      "frontmatter": {},
      "regularPath": "/guide/js/js%E5%B8%B8%E7%94%A8%E6%8A%80%E5%B7%A7.html",
      "relativePath": "guide/js/js常用技巧.md",
      "key": "v-6d45aedb",
      "path": "/guide/js/js%E5%B8%B8%E7%94%A8%E6%8A%80%E5%B7%A7.html",
      "lastUpdated": "8/29/2019, 11:17:42 AM"
    },
    {
      "title": "zh-CN",
      "frontmatter": {},
      "regularPath": "/zh-CN/guide/",
      "relativePath": "zh-CN/guide/README.md",
      "key": "v-fa665cdc",
      "path": "/zh-CN/guide/",
      "lastUpdated": "2019-8-29 4:56:00 PM"
    },
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroImage": "/img/favicon.png",
        "actionText": "开始学习 →",
        "actionLink": "/zh-CN/guide/",
        "features": [
          {
            "title": "简洁至上",
            "details": "以 Markdown 为中心的项目结构，以最少的配置帮助你专注于写作。"
          },
          {
            "title": "Vue驱动",
            "details": "享受 Vue + webpack 的开发体验，在 Markdown 中使用 Vue 组件，同时可以使用 Vue 来开发自定义主题。"
          },
          {
            "title": "高性能",
            "details": "VuePress 为每个页面预渲染生成静态的 HTML，同时在页面被加载的时候，将作为 SPA 运行。"
          }
        ],
        "footer": "MIT Licensed | Copyright © 2018-present Evan You"
      },
      "regularPath": "/zh-CN/",
      "relativePath": "zh-CN/README.md",
      "key": "v-659b7682",
      "path": "/zh-CN/",
      "lastUpdated": "2019-8-29 4:56:00 PM"
    },
    {
      "title": "优化 Vue 项目 中文",
      "frontmatter": {},
      "regularPath": "/zh-CN/guide/vue/%E4%BC%98%E5%8C%96Vue%E9%A1%B9%E7%9B%AE.html",
      "relativePath": "zh-CN/guide/vue/优化Vue项目.md",
      "key": "v-75ada1a6",
      "path": "/zh-CN/guide/vue/%E4%BC%98%E5%8C%96Vue%E9%A1%B9%E7%9B%AE.html",
      "lastUpdated": "2019-8-29 4:58:48 PM"
    },
    {
      "title": "常用的 JS 技巧",
      "frontmatter": {},
      "regularPath": "/zh-CN/guide/js/js%E5%B8%B8%E7%94%A8%E6%8A%80%E5%B7%A7.html",
      "relativePath": "zh-CN/guide/js/js常用技巧.md",
      "key": "v-286764a4",
      "path": "/zh-CN/guide/js/js%E5%B8%B8%E7%94%A8%E6%8A%80%E5%B7%A7.html",
      "lastUpdated": "2019-8-29 2:20:54 PM"
    },
    {
      "title": "Vue编码规范",
      "frontmatter": {},
      "regularPath": "/guide/vue/Vue%E7%BC%96%E7%A0%81%E8%A7%84%E8%8C%83.html",
      "relativePath": "guide/vue/Vue编码规范.md",
      "key": "v-6f28570b",
      "path": "/guide/vue/Vue%E7%BC%96%E7%A0%81%E8%A7%84%E8%8C%83.html",
      "lastUpdated": "8/29/2019, 11:17:42 AM"
    },
    {
      "title": "Vue编码规范 中文",
      "frontmatter": {},
      "regularPath": "/zh-CN/guide/vue/Vue%E7%BC%96%E7%A0%81%E8%A7%84%E8%8C%83.html",
      "relativePath": "zh-CN/guide/vue/Vue编码规范.md",
      "key": "v-02decf44",
      "path": "/zh-CN/guide/vue/Vue%E7%BC%96%E7%A0%81%E8%A7%84%E8%8C%83.html",
      "lastUpdated": "2019-8-29 4:58:48 PM"
    }
  ],
  "themeConfig": {
    "editLinks": true,
    "locales": {
      "/": {
        "selectText": "Languages",
        "lang": "en-US",
        "label": "English",
        "editLinkText": "Edit this page on GitHub",
        "lastUpdated": "Last Updated",
        "nav": [
          {
            "text": "home",
            "link": "/"
          },
          {
            "text": "blog",
            "link": "/guide/"
          }
        ],
        "sidebar": {
          "/guide/": [
            {
              "title": "Vue",
              "collapsable": false,
              "children": [
                [
                  "/guide/vue/优化Vue项目.md",
                  "优化Vue项目"
                ],
                [
                  "/guide/vue/Vue编码规范.md",
                  "Vue编码规范"
                ]
              ]
            },
            {
              "title": "React",
              "collapsable": false,
              "children": [
                [
                  "/guide/vue/优化Vue项目.md",
                  "优化Vue项目"
                ],
                [
                  "/guide/vue/Vue编码规范.md",
                  "Vue编码规范"
                ]
              ]
            }
          ]
        }
      },
      "/zh-CN/": {
        "selectText": "选择语言",
        "lang": "zh-CN",
        "label": "简体中文",
        "editLinkText": "在GitHub上编辑此页",
        "nav": [
          {
            "text": "首页",
            "link": "/zh-CN/"
          },
          {
            "text": "博客",
            "link": "/zh-CN/guide/"
          }
        ],
        "sidebar": {
          "/zh-CN/guide/": [
            {
              "title": "Vue",
              "collapsable": false,
              "children": [
                [
                  "/zh-CN/guide/vue/优化Vue项目.md",
                  "优化Vue项目"
                ],
                [
                  "/zh-CN/guide/vue/Vue编码规范.md",
                  "Vue编码规范"
                ]
              ]
            }
          ]
        }
      }
    }
  },
  "locales": {
    "/": {
      "lang": "en-US",
      "title": "Blog Jay",
      "description": "blog site of Jay",
      "path": "/"
    },
    "/zh-CN/": {
      "lang": "zh-CN",
      "title": "博客",
      "description": "赖维健的个人博客",
      "path": "/zh-CN/"
    }
  }
}