/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "",
  "description": "",
  "base": "/blog/",
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroImage": "/logo.JPG",
        "actionText": "Get Started →",
        "actionLink": "/guide/"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-62c2a688",
      "path": "/",
      "lastUpdated": "8/29/2019, 8:08:19 PM"
    },
    {
      "frontmatter": {},
      "regularPath": "/guide/",
      "relativePath": "guide/README.md",
      "key": "v-691e23ca",
      "path": "/guide/",
      "lastUpdated": "8/28/2019, 6:12:33 PM"
    },
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroImage": "/logo.JPG",
        "actionText": "开始学习 →",
        "actionLink": "/zh-CN/guide/"
      },
      "regularPath": "/zh-CN/",
      "relativePath": "zh-CN/README.md",
      "key": "v-659b7682",
      "path": "/zh-CN/",
      "lastUpdated": "2019-8-29 4:56:00 PM"
    },
    {
      "title": "123 zh-CN",
      "frontmatter": {},
      "regularPath": "/zh-CN/guide/js/123.html",
      "relativePath": "zh-CN/guide/js/123.md",
      "key": "v-7ecaf5ec",
      "path": "/zh-CN/guide/js/123.html"
    },
    {
      "title": "优化 Vue 项目 英文",
      "frontmatter": {},
      "regularPath": "/guide/vue/optimizeVue.html",
      "relativePath": "guide/vue/optimizeVue.md",
      "key": "v-6be1834e",
      "path": "/guide/vue/optimizeVue.html"
    },
    {
      "title": "优化 Vue 项目 中文",
      "frontmatter": {},
      "regularPath": "/zh-CN/guide/vue/optimizeVue.html",
      "relativePath": "zh-CN/guide/vue/optimizeVue.md",
      "key": "v-0d1e1c6c",
      "path": "/zh-CN/guide/vue/optimizeVue.html"
    },
    {
      "title": "zh-CN",
      "frontmatter": {},
      "regularPath": "/zh-CN/guide/",
      "relativePath": "zh-CN/guide/README.md",
      "key": "v-fa665cdc",
      "path": "/zh-CN/guide/",
      "lastUpdated": "2019-8-29 4:56:00 PM"
    }
  ],
  "themeConfig": {
    "editLinks": true,
    "locales": {
      "/": {
        "selectText": "Languages",
        "lang": "en-US",
        "label": "English",
        "editLinkText": "Edit this page on GitHub",
        "lastUpdated": "Last Updated",
        "nav": [
          {
            "text": "home",
            "link": "/"
          },
          {
            "text": "blog",
            "link": "/guide/"
          }
        ],
        "sidebar": {
          "/guide/": [
            {
              "title": "Vue",
              "collapsable": false,
              "children": [
                [
                  "/guide/vue/优化Vue项目.md",
                  "优化Vue项目"
                ],
                [
                  "/guide/vue/Vue编码规范.md",
                  "Vue编码规范"
                ]
              ]
            },
            {
              "title": "React",
              "collapsable": false,
              "children": [
                [
                  "/guide/vue/优化Vue项目.md",
                  "优化Vue项目"
                ],
                [
                  "/guide/vue/Vue编码规范.md",
                  "Vue编码规范"
                ]
              ]
            }
          ]
        }
      },
      "/zh-CN/": {
        "selectText": "选择语言",
        "lang": "zh-CN",
        "label": "简体中文",
        "editLinkText": "在GitHub上编辑此页",
        "nav": [
          {
            "text": "首页",
            "link": "/zh-CN/"
          },
          {
            "text": "博客",
            "link": "/zh-CN/guide/"
          }
        ],
        "sidebar": {
          "/zh-CN/guide/": [
            {
              "title": "Vue",
              "collapsable": false,
              "children": [
                [
                  "/zh-CN/guide/vue/优化Vue项目.md",
                  "优化Vue项目"
                ],
                [
                  "/zh-CN/guide/vue/Vue编码规范.md",
                  "Vue编码规范"
                ]
              ]
            }
          ]
        }
      }
    }
  },
  "locales": {
    "/": {
      "lang": "en-US",
      "title": "Blog Jay",
      "description": "blog site of Jay",
      "path": "/"
    },
    "/zh-CN/": {
      "lang": "zh-CN",
      "title": "博客",
      "description": "赖维健的个人博客",
      "path": "/zh-CN/"
    }
  }
}